In [1]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/ektanegi25/Credit-Card-Fraud-Detection/main/creditCardFraud_28011964_120214.csv")
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0

In [2]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT4                   1001 non-null   int64
 15  BILL_AMT5                   1001 non-null   int64
 16  BILL_AMT6                   1001 non-null   int64
 17  PAY_AMT1                    1001 non-null   int64
 18  PAY_AMT2                    1001 non-null   int64
 19  PAY_AMT3                    1001 non-null   int64
 20  PAY_AMT4                    1001 non-null   int64
 21  PAY_AMT5                    1001 non-null   int64
 22  PAY_AMT6                    1001 non-null   int64
 23  default payment next month  1001 non-null   int64
dtypes: int64(24)
memory usage: 187.8 KB

In [4]:
df.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,...,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000
mean,167532.467532,1.589411,1.776224,1.604396,34.945055,-0.004995,-0.161838,-0.164835,-0.283716,-0.283716,...,40748.408591,39078.666334,38012.011988,5382.339660,5051.400599,4176.149850,4671.488511,5331.049950,5090.704296,0.213786
std,130587.921320,0.492187,0.750916,0.532298,9.219760,1.173446,1.228732,1.262459,1.184662,1.170224,...,68206.929510,63108.238729,63074.415024,12180.755275,15626.153184,10514.647502,13269.943983,16812.536877,23658.888052,0.410183
min,10000.000000,1.000000,1.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-3684.000000,-28335.000000,-339603.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1423.000000,1206.000000,830.000000,1000.000000,390.000000,228.000000,148.000000,189.000000,0.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17710.000000,17580.000000,15846.000000,2184.000000,1710.000000,1206.000000,1398.000000,1306.000000,1250.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,48851.000000,46404.000000,46557.000000,5090.000000,4500.000000,3720.000000,4000.000000,3745.000000,3784.000000,0.000000
max,700000.000000,2.000000,6.000000,3.000000,75.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,628699.000000,484612.000000,473944.000000,199646.000000,285138.000000,133657.000000,188840.000000,195599.000000,528666.000000,1.000000

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
LIMIT_BAL,1001.0,167532.467532,130587.921320,10000.0,50000.0,140000.0,240000.0,700000.0
SEX,1001.0,1.589411,0.492187,1.0,1.0,2.0,2.0,2.0
EDUCATION,1001.0,1.776224,0.750916,1.0,1.0,2.0,2.0,6.0
MARRIAGE,1001.0,1.604396,0.532298,0.0,1.0,2.0,2.0,3.0
AGE,1001.0,34.945055,9.219760,21.0,28.0,33.0,41.0,75.0
PAY_0,1001.0,-0.004995,1.173446,-2.0,-1.0,0.0,0.0,8.0
PAY_2,1001.0,-0.161838,1.228732,-2.0,-1.0,0.0,0.0,7.0
PAY_3,1001.0,-0.164835,1.262459,-2.0,-1.0,0.0,0.0,7.0
PAY_4,1001.0,-0.283716,1.184662,-2.0,-1.0,0.0,0.0,7.0
PAY_5,1001.0,-0.283716,1.170224,-2.0,-1.0,0.0,0.0,7.0
PAY_6,1001.0,-0.314685,1.203276,-2.0,-1.0,0.0,0.0,7.0
BILL_AMT1,1001.0,49386.738262,72657.966256,-14386.0,3128.0,21075.0,59901.0,507726.0
BILL_AMT2,1001.0,47879.345654,72090.718188,-13543.0,3274.0,20400.0,58472.0,509229.0
BILL_AMT3,1001.0,44925.682318,69545.948045,-9850.0,1940.0,19292.0,54477.0,499936.0
BILL_AMT4,1001.0,40748.408591,68206.929510,-3684.0,1423.0,17710.0,48851.0,628699.0
BILL_AMT5,1001.0,39078.666334,63108.238729,-28335.0,1206.0,17580.0,46404.0,484612.0
BILL_AMT6,1001.0,38012.011988,63074.415024,-339603.0,830.0,15846.0,46557.0,473944.0
PAY_AMT1,1001.0,5382.339660,12180.755275,0.0,1000.0,2184.0,5090.0,199646.0
PAY_AMT2,1001.0,5051.400599,15626.153184,0.0,390.0,1710.0,4500.0,285138.0
PAY_AMT3,1001.0,4176.149850,10514.647502,0.0,228.0,1206.0,3720.0,133657.0
PAY_AMT4,1001.0,4671.488511,13269.943983,0.0,148.0,1398.0,4000.0,188840.0
PAY_AMT5,1001.0,5331.049950,16812.536877,0.0,189.0,1306.0,3745.0,195599.0
PAY_AMT6,1001.0,5090.704296,23658.888052,0.0,0.0,1250.0,3784.0,528666.0
default payment next month,1001.0,0.213786,0.410183,0.0,0.0,0.0,0.0,1.0

In [10]:
!pip install pandas-profiling

Requirement already satisfied: pandas-profiling in /Users/ekta/anaconda3/lib/python3.11/site-packages (3.2.0)
Requirement already satisfied: joblib~=1.1.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.1.1)
Requirement already satisfied: scipy>=1.4.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib>=3.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.7.1)
Requirement already satisfied: pydantic>=1.8.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.4.2)
Requirement already satisfied: PyYAML>=5.0.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (6.0)
Requirement already satisfied: jinja2>=2.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.1.2)
Requirement already satisfied: markupsafe~=2.1.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.1.1)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.24.3)
Requirement already satisfied: htmlmin>=0.1.12 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.5.2)
Requirement already satisfied: phik>=0.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.3)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.29.0)
Requirement already satisfied: tqdm>=4.48.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn>=0.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod>=1.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10)
Requirement already satisfied: attrs>=19.3.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (22.1.0)
Requirement already satisfied: networkx>=2.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.8.4)
Requirement already satisfied: imagehash in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.1)
Requirement already satisfied: Pillow in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2022.7)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic>=1.8.1->pandas-profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic>=1.8.1->pandas-profiling) (2.10.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic>=1.8.1->pandas-profiling) (4.6.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2023.5.7)
Requirement already satisfied: six>=1.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.16.0)
Requirement already satisfied: PyWavelets in /Users/ekta/anaconda3/lib/python3.11/site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.4.1)

In [16]:
from pandas_profiling import ProfileReport


profile = ProfileReport(df, title = "Pandas Profiling Report")
profile

PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.4/migration/#basesettings-has-moved-to-pydantic-settings for more details.

For further information visit https://errors.pydantic.dev/2.4/u/import-error

In [9]:
!pip install --upgrade pydantic pandas-profiling

Requirement already satisfied: pydantic in /Users/ekta/anaconda3/lib/python3.11/site-packages (2.4.2)
Requirement already satisfied: pandas-profiling in /Users/ekta/anaconda3/lib/python3.11/site-packages (3.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (0.6.0)
Requirement already satisfied: pydantic-core==2.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (2.10.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (4.6.3)
Requirement already satisfied: joblib~=1.1.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.1.1)
Requirement already satisfied: scipy>=1.4.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib>=3.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.7.1)
Requirement already satisfied: PyYAML>=5.0.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (6.0)
Requirement already satisfied: jinja2>=2.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.1.2)
Requirement already satisfied: markupsafe~=2.1.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.1.1)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.24.3)
Requirement already satisfied: htmlmin>=0.1.12 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.5.2)
Requirement already satisfied: phik>=0.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.3)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.29.0)
Requirement already satisfied: tqdm>=4.48.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn>=0.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod>=1.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10)
Requirement already satisfied: attrs>=19.3.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (22.1.0)
Requirement already satisfied: networkx>=2.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.8.4)
Requirement already satisfied: imagehash in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.1)
Requirement already satisfied: Pillow in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2022.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2023.5.7)
Requirement already satisfied: six>=1.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.16.0)
Requirement already satisfied: PyWavelets in /Users/ekta/anaconda3/lib/python3.11/site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.4.1)

In [15]:
! pip install --upgrade pydantic pandas-profiling

Requirement already satisfied: pydantic in /Users/ekta/anaconda3/lib/python3.11/site-packages (2.4.2)
Requirement already satisfied: pandas-profiling in /Users/ekta/anaconda3/lib/python3.11/site-packages (3.2.0)
Requirement already satisfied: annotated-types>=0.4.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (0.6.0)
Requirement already satisfied: pydantic-core==2.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (2.10.1)
Requirement already satisfied: typing-extensions>=4.6.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pydantic) (4.6.3)
Requirement already satisfied: joblib~=1.1.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.1.1)
Requirement already satisfied: scipy>=1.4.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10.1)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.5.3)
Requirement already satisfied: matplotlib>=3.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.7.1)
Requirement already satisfied: PyYAML>=5.0.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (6.0)
Requirement already satisfied: jinja2>=2.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (3.1.2)
Requirement already satisfied: markupsafe~=2.1.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.1.1)
Requirement already satisfied: visions[type_image_path]==0.7.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.7.4)
Requirement already satisfied: numpy>=1.16.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.24.3)
Requirement already satisfied: htmlmin>=0.1.12 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.1.12)
Requirement already satisfied: missingno>=0.4.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.5.2)
Requirement already satisfied: phik>=0.11.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.3)
Requirement already satisfied: tangled-up-in-unicode==0.2.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.2.0)
Requirement already satisfied: requests>=2.24.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (2.29.0)
Requirement already satisfied: tqdm>=4.48.2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (4.65.0)
Requirement already satisfied: seaborn>=0.10.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (0.12.2)
Requirement already satisfied: multimethod>=1.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas-profiling) (1.10)
Requirement already satisfied: attrs>=19.3.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (22.1.0)
Requirement already satisfied: networkx>=2.4 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (2.8.4)
Requirement already satisfied: imagehash in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (4.3.1)
Requirement already satisfied: Pillow in /Users/ekta/anaconda3/lib/python3.11/site-packages (from visions[type_image_path]==0.7.4->pandas-profiling) (9.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (23.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.2.0->pandas-profiling) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,!=1.1.0,>=0.25.3->pandas-profiling) (2022.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from requests>=2.24.0->pandas-profiling) (2023.5.7)
Requirement already satisfied: six>=1.5 in /Users/ekta/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->pandas-profiling) (1.16.0)
Requirement already satisfied: PyWavelets in /Users/ekta/anaconda3/lib/python3.11/site-packages (from imagehash->visions[type_image_path]==0.7.4->pandas-profiling) (1.4.1)

In [ ]:
import